config/routes.rb
Rails.application.routes.draw do
  root :to => redirect('search')

  get 'search' => 'hotels#search'

  resources :hotels

end

app/models/hotel.rb
class Hotel < ActiveRecord::Base
  def self.search(search)
    if search
      self.where("location like ?", "%#{search}%")
    else
      self.all
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
  before_action :set_hotel, only: [:show, :edit, :update, :destroy]

  # GET /hotels
  # GET /hotels.json
  def index
    @hotels = Hotel.all
  end

  def search
    @hotels = Hotel.search(params[:location])
  end

  # GET /hotels/1
  # GET /hotels/1.json
  def show
  end

  # GET /hotels/new
  def new
    @hotel = Hotel.new
  end

  # GET /hotels/1/edit
  def edit
  end

  # POST /hotels
  # POST /hotels.json
  def create
    @hotel = Hotel.new(hotel_params)

    respond_to do |format|
      if @hotel.save
        format.html { redirect_to @hotel, notice: 'Hotel was successfully created.' }
        format.json { render :show, status: :created, location: @hotel }
      else
        format.html { render :new }
        format.json { render json: @hotel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hotels/1
  # PATCH/PUT /hotels/1.json
  def update
    respond_to do |format|
      if @hotel.update(hotel_params)
        format.html { redirect_to @hotel, notice: 'Hotel was successfully updated.' }
        format.json { render :show, status: :ok, location: @hotel }
      else
        format.html { render :edit }
        format.json { render json: @hotel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hotels/1
  # DELETE /hotels/1.json
  def destroy
    @hotel.destroy
    respond_to do |format|
      format.html { redirect_to hotels_url, notice: 'Hotel was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hotel
      @hotel = Hotel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hotel_params
      params.require(:hotel).permit(:name, :location, :unavailable)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/views/hotels/_form.html.erb
<%= form_for(@hotel) do |f| %>
  <% if @hotel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@hotel.errors.count, "error") %> prohibited this hotel from being saved:</h2>

      <ul>
      <% @hotel.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :unavailable %><br>
    <%= f.text_field :unavailable %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/hotels/edit.html.erb
<h1>Editing Hotel</h1>

<%= render 'form' %>

<%= link_to 'Show', @hotel %> |
<%= link_to 'Back', hotels_path %>

app/views/hotels/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Hotels</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Location</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @hotels.each do |hotel| %>
      <tr>
        <td><%= hotel.name %></td>
        <td><%= hotel.location %></td>
        <td><%= hotel.unavailable %></td>
        <td><%= link_to 'Show', hotel %></td>
        <td><%= link_to 'Edit', edit_hotel_path(hotel) %></td>
        <td><%= link_to 'Destroy', hotel, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Hotel', new_hotel_path %>

app/views/hotels/new.html.erb
<h1>New Hotel</h1>

<%= render 'form' %>

<%= link_to 'Back', hotels_path %>

app/views/hotels/search.html.erb
<p id="notice"><%= notice %></p>

<h1>Search</h1>

<%= form_tag search_path, :method => 'get' do %>
  <p>
    <%= text_field_tag :location, params[:location], :placeholder => 'Digite a cidade de destino', :style => 'width: 200px', :list => 'locations' %>

    <datalist id="locations">
      <option value="Rio de Janeiro">
      <option value="São Paulo">
    </datalist>


    <%= submit_tag "Search", :name => nil %>
  </p>
<% end %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Location</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @hotels.each do |hotel| %>
      <tr>
        <td><%= hotel.name %></td>
        <td><%= hotel.location %></td>
        <td><%= link_to 'Show', hotel %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/hotels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @hotel.name %>
</p>

<p>
  <strong>Location:</strong>
  <%= @hotel.location %>
</p>

<p>
  <strong>Unavailable:</strong>
  <%= @hotel.unavailable %>
</p>

<%= link_to 'Edit', edit_hotel_path(@hotel) %> |
<%= link_to 'Back to Hotels', hotels_path %> |
<%= link_to 'Back to Search', root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SearchHotel</title>
</head>
<body>

<ul>
	<li><%= link_to 'Busca', search_path %></li>
	<li><%= link_to 'Hotels', hotels_path %></li>
</ul>

<%= yield %>

</body>
</html>